apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: cars.stable.pirix.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.pirix.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: cars
    # singular name to be used as an alias on the CLI and for display
    singular: car
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: F1
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - f1
  subresources:
    status: {}
  # Kubernetes starts using server side printing since 1.11, i.e. server decides what
  # to show when `Kubectl get` issued
  additionalPrinterColumns:
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: Replicas
      type: integer
      description: The number of jobs launched by the F1
      JSONPath: .spec.replicas
    - name: EngineClass
      type: string
      description: The engine class spec defining how powerful engine is
      JSONPath: .spec.engineClass
    - name: Image
      type: string
      description: The image being running
      JSONPath: .spec.image
